version: "3.8"
services:
  app:
    container_name: rekam_medis
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    volumes:
      - ./:/var/www/app
      - vendor_app:/var/www/app/vendor
      - ./docker/99-upload-config.ini:/usr/local/etc/php/conf.d/99-upload-config.ini
    networks:
      - pds
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: rekam_medis_nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - '${FORWARD_NGINX_PORT:-8110}:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./:/var/www/app
    depends_on:
      - app
    networks:
      - pds
networks:
  pds:
    driver: bridge
    
volumes:
  vendor_app:
